CREATE TABLE u122030_order_recharge
(
    id VARCHAR(64) NOT NULL COMMENT '支付流水ID',
    order_id VARCHAR(64) NOT NULL COMMENT '玩家订单ID',
    user_id VARCHAR(64) NOT NULL COMMENT '玩家ID',
    user_nickname VARCHAR(80) NOT NULL COMMENT '玩家昵称',
    user_phone VARCHAR(40) NOT NULL COMMENT '玩家手机号',
    pay_reason_code VARCHAR(4) DEFAULT '1' COMMENT '订单支付类别编码(1充值2购买)',
    pay_reason_name VARCHAR(20) DEFAULT '充值' COMMENT '订单支付类别说明',
    open_id VARCHAR(128) COMMENT '第三方唯一标识',
    nonce_str VARCHAR(120) COMMENT '订单校验码',
    body VARCHAR(400) COMMENT '订单描述',
    pay_trade_no VARCHAR(64) NOT NULL COMMENT '商户支付订单ID（UUID）',
    pay_type_code VARCHAR(4) COMMENT '支付方式编码(1:支付宝支付2:微信支付3:支付宝h5支付4:微信扫码支付5:微信公众号支付)',
    pay_type_name VARCHAR(20) COMMENT '支付方式说明(1:支付宝支付2:微信支付3:支付宝h5支付4:微信扫码支付5:微信公众号支付)',
    pay_account VARCHAR(80) COMMENT '支付账户ID',
    pay_account_name VARCHAR(40) COMMENT '支付账号人姓名',
    pay_account_phone VARCHAR(20) COMMENT '支付账号手机号',
    pay_sec_code VARCHAR(20) COMMENT '支付账号绑定验证码',
    pay_amount DECIMAL(10,2) COMMENT '支付金额',
    pay_state_code VARCHAR(4) DEFAULT '2' COMMENT '支付状态编码（1已支付,2未支付）',
    pay_state_name VARCHAR(20) DEFAULT '未支付' COMMENT '支付状态说明',
    pay_number VARCHAR(128) COMMENT '第三方支付流水号',
    pay_date VARCHAR(10) COMMENT '支付日期',
    pay_time VARCHAR(14) COMMENT '支付时间',
    order_state_code VARCHAR(4) DEFAULT '2' COMMENT '到账状态编码（1已到账,2未到账）',
    order_state_name VARCHAR(20) DEFAULT '未到账' COMMENT '到账状态说明',
    order_time VARCHAR(24) COMMENT '到账时间',
    is_supplement VARCHAR(4) DEFAULT '2' COMMENT '是否需要补单(2需要,1不需要)',
    order_supplement_time VARCHAR(24) COMMENT '补单发货时间',
    process_name VARCHAR(80) COMMENT '到账后业务实现类名',
    funcation_name VARCHAR(80) COMMENT '到账后业务实现方法名称',
    memo VARCHAR(200) COMMENT '备注',
    fb1 VARCHAR(40) COMMENT '备用1',
    fb2 VARCHAR(20) COMMENT '备用2',
    fb3 VARCHAR(50) COMMENT '备用3',
    fb4 VARCHAR(200) COMMENT '备用4',
    fb5 VARCHAR(80) COMMENT '备用5',
    eb1 VARCHAR(40) COMMENT '扩展1',
    eb2 VARCHAR(80) COMMENT '扩展2',
    eb3 VARCHAR(20) COMMENT '扩展3',
    eb4 VARCHAR(10) COMMENT '扩展4',
    eb5 VARCHAR(20) COMMENT '扩展5',
    hdp VARCHAR(20) COMMENT '数据归属系统',
    del_flag CHAR(1) DEFAULT '0' COMMENT '有效标识',
    create_time VARCHAR(24) DEFAULT '2018-02-02' NOT NULL COMMENT '创建时间',
    creator VARCHAR(64) DEFAULT 'SYSTEM' NOT NULL COMMENT '创建者',
    update_time VARCHAR(24) COMMENT '更新时间',
    updator VARCHAR(64) COMMENT '最后更新者',
PRIMARY KEY (id)
) COMMENT '玩家订单支付信息'
;
