CREATE TABLE s901030_menu
(
    puk VARCHAR(20) NOT NULL COMMENT '流水ID',
    father_menu_id VARCHAR(20) COMMENT '父菜单流水ID',
    menu_name VARCHAR(40) COMMENT '菜单名称',
    menu_ver VARCHAR(20) COMMENT '菜单版本号',
    sort_num BIGINT(20) COMMENT '排列顺序',
    menu_pic_url VARCHAR(80) COMMENT '菜单图标',
    menu_url VARCHAR(200) COMMENT '菜单URL',
    menu_level VARCHAR(4) COMMENT '菜单等级',
    menu_type VARCHAR(20) COMMENT '菜单类别',
    next_sub VARCHAR(4) COMMENT '下级菜单数目',
    meno VARCHAR(200) COMMENT '备注',
    fb1 VARCHAR(40) COMMENT '备用1',
    fb2 VARCHAR(20) COMMENT '备用2',
    fb3 VARCHAR(20) COMMENT '备用3',
    fb4 VARCHAR(200) COMMENT '备用4',
    fb5 VARCHAR(20) COMMENT '备用5',
    eb1 VARCHAR(40) COMMENT '扩展1',
    eb2 VARCHAR(80) COMMENT '扩展2',
    eb3 VARCHAR(20) COMMENT '扩展3',
    eb4 VARCHAR(10) COMMENT '扩展4',
    eb5 VARCHAR(20) COMMENT '扩展5',
    hdp VARCHAR(20) COMMENT '数据归属系统',
    del_flag CHAR(1) DEFAULT '0' COMMENT '有效标识',
    create_time VARCHAR(24) DEFAULT '2017-12-12' NOT NULL COMMENT '创建时间',
    creator VARCHAR(20) DEFAULT 'SYSTEM' NOT NULL COMMENT '创建者',
    update_time VARCHAR(24) COMMENT '更新时间',
    updator VARCHAR(20) COMMENT '最后更新者',
PRIMARY KEY (puk)
) COMMENT '系统菜单'
;
