##注册中心服务地址(必须把自己注册上去，才有权限获取)
eureka:
  client:
    serviceUrl:
      defaultZone: http://crm:123456@172.16.8.225:7000/eureka/ #/eureka注册地址绝对不能缺少
##当前服务端口      
server:
  port: 8810
spring:
  application:
    name: SC-ZT-Zuul-Service
  datasource:
    name: mysql
    url: jdbc:mysql://rm-bp1zd1dgr35n73z64.mysql.rds.aliyuncs.com:3306/zylc_test?useUnicode=yes&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: purchase
    password: hnALGRX0C1pUge
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: r-bp13140e7f1dafe4.redis.rds.aliyuncs.com
    password: snHHCtxUFCgOm5
    port: 6379
    database: 8
    jedis:
      pool:
        max-active: 100
        max-idle: 20
        max-wait: 20
        min-idle: 10
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
      
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapperLocations: classpath*:com/*/*/persistent/*/*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.*.*.persistent.*.*  # 注意：对应实体类的路径
  configuration:
    mapUnderscoreToCamelCase: true
  
## 日志输出范围配置
logging:
  config: classpath:logback-string.xml
  path: /mnt/log
  file: serverUser.log
  level:
    com.lcgj: info
    com.camelot: info
    com.camelot.framework.log: error
    com.camelot.framework.utils: error
    com.camelot.framework.config: error
    springfox.documentation: error
    org.mybatis: error
    org.apache: error
    com.alibaba: error
    com.netflix: error
    org.springframework: error
    org.quartz: error
    net.sf: error
    
## 自定义参数------------------------------------------------------------------------------------
h5: ## H5参数配置
  config:
    webServerUrl: http://uatuser.gtdreamlife.com
    apiServerUrl: http://uatuser.gtdreamlife.com
    wxAppID: debug
    wxAppSecret: debug

model:
  type: uat
rool: ## 权限验证
  admin: admin      #超级管理员账号
  check: false   
sms:
  publicServer: http://api.china95059.net:8080/sms/send
  
oss:
  publicServer: http://gtcloud-center.oss-cn-hangzhou.aliyuncs.com/
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  outputQuality: 0.5
  scale: 0.5
  
login: ## 融合平台登录
  platformWebserviceUrl: http://md-sit.gtcloud.cn:82/Webservice/UserInfoDeal.asmx/UserInfoQuery?userLoginId=
  
rhpt:
  orgApi: http://sscorg.gtcloud.cn/ssc-org
  partnerId: 1004
  partnerSecret: 07b6334651a043b699617f8aa08fcbc1
  bsid: CRM_SYS
  
logData:   ##日志输出
  logServiceURL: http://183.134.76.127:8810/log/append
  logEnable: true
  