CREATE TABLE u122020_order_goods
(
    id VARCHAR(64) NOT NULL COMMENT 'ID',
    order_id VARCHAR(64) NOT NULL COMMENT '玩家订单ID',
    merchant_id VARCHAR(64) COMMENT '商户ID',
    merchant_name VARCHAR(100) COMMENT '商户名称',
    goods_id VARCHAR(80) COMMENT '产品ID',
    goods_name VARCHAR(80) COMMENT '产品名称',
    goods_publish_id VARCHAR(64) COMMENT '商品发布ID',
    goods_publish_name VARCHAR(80) COMMENT '商品发布名称',
    goods_publish_specs_id VARCHAR(64) COMMENT '商品发布规格ID',
    goods_publish_specs_name VARCHAR(200) COMMENT '商品发布规格名称',
    market_price DECIMAL(10,2) COMMENT '市场价格(标价)',
    goods_price DECIMAL(10,2) COMMENT '商品价格(卖价)',
    buy_num BIGINT(10) COMMENT '购买数量',
    goods_status_code VARCHAR(4) DEFAULT '1' COMMENT '商品状态编码(1待发货2已发货3缺货取消9退货)',
    goods_status_name VARCHAR(20) COMMENT '商品状态说明',
    memo VARCHAR(200) COMMENT '备注',
    fb1 VARCHAR(40) COMMENT '备用1',
    fb2 VARCHAR(20) COMMENT '备用2',
    fb3 VARCHAR(50) COMMENT '备用3',
    fb4 VARCHAR(200) COMMENT '备用4',
    fb5 VARCHAR(80) COMMENT '备用5',
    eb1 VARCHAR(40) COMMENT '扩展1',
    eb2 VARCHAR(80) COMMENT '扩展2',
    eb3 VARCHAR(20) COMMENT '扩展3',
    eb4 VARCHAR(10) COMMENT '扩展4',
    eb5 VARCHAR(20) COMMENT '扩展5',
    hdp VARCHAR(20) COMMENT '数据归属系统',
    del_flag CHAR(1) DEFAULT '0' COMMENT '有效标识',
    create_time VARCHAR(24) DEFAULT '2018-02-02' NOT NULL COMMENT '创建时间',
    creator VARCHAR(64) DEFAULT 'SYSTEM' NOT NULL COMMENT '创建者',
    update_time VARCHAR(24) COMMENT '更新时间',
    updator VARCHAR(64) COMMENT '最后更新者',
PRIMARY KEY (id)
) COMMENT '订单商品详情表'
;
