CREATE TABLE u101010_user_info
(
    puk VARCHAR(20) NOT NULL COMMENT '玩家流水ID',
    channel_type VARCHAR(20) COMMENT '渠道标识',
    register_type VARCHAR(4) COMMENT '注册方式',
    user_phone VARCHAR(20) COMMENT '手机号',
    wx_open_id VARCHAR(80) COMMENT '微信ID',
    qq_open_id VARCHAR(80) COMMENT 'QQID',
    nick_name VARCHAR(80) COMMENT '昵称',
    head_portrait_url VARCHAR(200) COMMENT '头像URL',
    sex VARCHAR(4) DEFAULT '0' COMMENT '性别',
    age_group VARCHAR(4) COMMENT '年龄段',
    education VARCHAR(4) COMMENT '学历',
    birthday VARCHAR(20) COMMENT '生日',
    mailbox VARCHAR(40) COMMENT '邮箱',
    real_name VARCHAR(40) COMMENT '真实姓名',
    id_card VARCHAR(80) COMMENT '身份证号码',
    real_photo VARCHAR(200) COMMENT '本人真实照片',
    apply_state_nick VARCHAR(4) COMMENT '昵称审核状态',
    apply_state_head VARCHAR(4) COMMENT '头像审核状态',
    apply_state_real VARCHAR(4) DEFAULT '9' COMMENT '实名审核状态',
    state VARCHAR(4) DEFAULT '0' COMMENT '账号状态',
    meno VARCHAR(200) COMMENT '备注',
    fb1 VARCHAR(40) COMMENT '备用1',
    fb2 VARCHAR(20) COMMENT '备用2',
    fb3 VARCHAR(20) COMMENT '备用3',
    fb4 VARCHAR(200) COMMENT '备用4',
    fb5 VARCHAR(20) COMMENT '备用5',
    eb1 VARCHAR(40) COMMENT '扩展1',
    eb2 VARCHAR(80) COMMENT '扩展2',
    eb3 VARCHAR(20) COMMENT '扩展3',
    eb4 VARCHAR(10) COMMENT '扩展4',
    eb5 VARCHAR(20) COMMENT '扩展5',
    del_flag CHAR(1) DEFAULT '0' NOT NULL COMMENT '有效标识',
    create_time VARCHAR(24) DEFAULT '2017/11/12 23:00:00' NOT NULL COMMENT '创建时间',
    creator VARCHAR(20) DEFAULT 'SYSTEM' NOT NULL COMMENT '创建者',
    update_time VARCHAR(24) DEFAULT '2017/11/12 23:00:00' COMMENT '更新时间',
    updator VARCHAR(20) COMMENT '最后更新者',
PRIMARY KEY (puk)
) COMMENT '玩家基本信息'
;
