CREATE TABLE u122010_order
(
    id VARCHAR(64) NOT NULL COMMENT '玩家订单ID',
    order_no VARCHAR(128) COMMENT '第三方订单唯一编号',
    channel_id VARCHAR(64) DEFAULT 'SYSTEM' COMMENT '玩家渠道ID',
    user_id VARCHAR(64) NOT NULL COMMENT '玩家ID',
    user_nickname VARCHAR(80) NOT NULL COMMENT '玩家昵称',
    user_phone VARCHAR(40) NOT NULL COMMENT '玩家手机号',
    machine_id VARCHAR(64) COMMENT '设备ID',
    machine_type_code VARCHAR(4) COMMENT '设备类型编码',
    machine_type_name VARCHAR(20) COMMENT '设备类型说明',
    order_type_code VARCHAR(4) DEFAULT '1' COMMENT '订单类型编码',
    order_typee_name VARCHAR(20) COMMENT '订单类型说明',
    order_date VARCHAR(24) COMMENT '订单日期',
    order_time VARCHAR(24) COMMENT '订单时间',
    goods_cost DECIMAL(10,2) COMMENT '商品总额',
    transport_cost DECIMAL(10,2) COMMENT '运费',
    order_total_cost DECIMAL(10,2) COMMENT '订单总额',
    is_discount VARCHAR(4) COMMENT '是否有折扣',
    discounts_cost DECIMAL(10,2) COMMENT '返现',
    reality_cost DECIMAL(10,2) COMMENT '优惠券',
    pay_amount DECIMAL(20,2) COMMENT '待支付金额',
    is_recharge VARCHAR(4) DEFAULT '2' COMMENT '是否需要支付(2需要,1不需要)',
    recharge_type_code VARCHAR(4) COMMENT '支付方式编码(1:支付宝支付2:微信支付3:支付宝h5支付4:微信扫码支付5:微信公众号支付)',
    order_recharge_id VARCHAR(64) COMMENT '订单支付流水ID',
    recharge_money DECIMAL(10,2) COMMENT '实际支付金额',
    recharge_state_code VARCHAR(4) DEFAULT '2' COMMENT '支付状态（1已支付,2未支付）',
    recharge_order_state_code VARCHAR(4) DEFAULT '2' COMMENT '到账状态编码（1已到账,2未到账）',
    is_after_sale VARCHAR(4) DEFAULT '2' COMMENT '是否需要售后(2需要,1不需要)',
    order_aftersale_id VARCHAR(64) COMMENT '售后流水ID',
    after_sale_state_code VARCHAR(4) DEFAULT '1' COMMENT '售后状态编码(1正常, 6待出库, 9已完成)',
    is_supplement VARCHAR(4) DEFAULT '2' COMMENT '是否需要补单(2需要,1不需要)',
    order_supplement_time VARCHAR(24) COMMENT '补单发货时间',
    is_express VARCHAR(4) DEFAULT '1' COMMENT '是否需要快递配送(1:不需要；2：需要)',
    order_express_id VARCHAR(64) COMMENT '快递配送流水ID',
    express_no VARCHAR(64) COMMENT '快递单号',
    express_company VARCHAR(120) COMMENT '快递公司',
    order_status_code VARCHAR(4) DEFAULT '1' COMMENT '订单状态编码(1待付款, 2已取消, 3已付款待处理, 4申请退款, 5退款确认,6已发货, 7物流配送中, 8申请售后, 9售后退款, 10已完成)',
    order_status_name VARCHAR(20) DEFAULT '待付款' COMMENT '订单状态说明',
    process_name VARCHAR(80) COMMENT '业务实现类名',
    funcation_name VARCHAR(80) COMMENT '业务实现方法名称',
    nonce_str VARCHAR(120) COMMENT '订单校验码',
    body VARCHAR(400) COMMENT '订单描述',
    memo VARCHAR(200) COMMENT '备注',
    fb1 VARCHAR(40) COMMENT '备用1',
    fb2 VARCHAR(20) COMMENT '备用2',
    fb3 VARCHAR(50) COMMENT '备用3',
    fb4 VARCHAR(200) COMMENT '备用4',
    fb5 VARCHAR(80) COMMENT '备用5',
    eb1 VARCHAR(40) COMMENT '扩展1',
    eb2 VARCHAR(80) COMMENT '扩展2',
    eb3 VARCHAR(20) COMMENT '扩展3',
    eb4 VARCHAR(10) COMMENT '扩展4',
    eb5 VARCHAR(20) COMMENT '扩展5',
    hdp VARCHAR(20) COMMENT '数据归属系统',
    del_flag CHAR(1) DEFAULT '0' COMMENT '有效标识',
    create_time VARCHAR(24) DEFAULT '2018-02-02' NOT NULL COMMENT '创建时间',
    creator VARCHAR(64) DEFAULT 'SYSTEM' NOT NULL COMMENT '创建者',
    update_time VARCHAR(24) COMMENT '更新时间',
    updator VARCHAR(64) COMMENT '最后更新者',
PRIMARY KEY (id)
) COMMENT '订单信息表'
;
