##注册中心服务地址(必须把自己注册上去，才有权限获取)
eureka:
  client:
    serviceUrl:
      defaultZone: http://zmsoft:123456@127.0.0.1:11111/eureka/ #/eureka注册地址绝对不能缺少
##当前服务端口
server:
  port: 6666
  tomcat:
    max-http-post-size: -1
spring:
  application:
    name: CN-Eureka-Server
  datasource:
    name: mysql
    url: jdbc:mysql://192.168.1.201:3306/fcy_dev?useUnicode=yes&characterEncoding=utf8&autoReconnect=true #&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: zaq12wsx
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.201
    password: zaq12wsx
    port: 6379
    database: 5
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
      
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapperLocations: #注意：一定要对应mapper映射xml文件的所在路径
    classpath*:org/*/persistent/*/*/*.xml
    classpath*:com/*/persistent/*/*/*.xml
  typeAliasesPackage: # 注意：对应实体类的路径
    org.*.persistent.*.*
    com.*.persistent.*.*
  configuration:
    mapUnderscoreToCamelCase: true
  
## 日志输出范围配置
logging:
  #config: classpath:logback.xml
  #path: /mnt/log
  #file: serverUser.log
  level:
    org.zmsoft: debug
    com.zmsoft: debug
    com.qmsoft: debug
    org.zmsoft.config.system: info
    org.zmsoft.framework.db: info
    org.zmsoft.framework.log: error
    org.zmsoft.framework.utils: error
    org.zmsoft.framework.config: error
    org.zmsoft.framework.support: debug
    springfox.documentation: error
    org.mybatis: error
    org.apache: error
    com.alibaba: error
    com.netflix: error
    org.springframework: error
    org.quartz: error
    
## 自定义参数------------------------------------------------------------------------------------
model:
  id: 10