CREATE TABLE u201010_company_info
(
    puk VARCHAR(20) NOT NULL COMMENT '流水ID',
    company_name VARCHAR(120) COMMENT '公司名称',
    company_code VARCHAR(40) COMMENT '统一社会信息用代码',
    company_address_country VARCHAR(80) COMMENT '公司注册地址（国家）',
    company_address_province VARCHAR(40) COMMENT '公司注册地址（省）',
    company_address_city VARCHAR(40) COMMENT '公司注册地址（市）',
    company_address_area VARCHAR(40) COMMENT '公司注册地址（区）',
    company_address VARCHAR(200) COMMENT '公司注册地址（街道）',
    business_license_copy VARCHAR(200) COMMENT '营业执照(副本)URL',
    corporation_name VARCHAR(20) COMMENT '法人姓名',
    corporation_phone VARCHAR(20) COMMENT '法人电话',
    legal_person_idcard_front VARCHAR(200) COMMENT '法人身份证(正面)URL',
    legal_person_idcard_back VARCHAR(200) COMMENT '法人身份证(反面)URL',
    contact_idcard_front VARCHAR(200) COMMENT '联系人身份证(正面)URL',
    contact_idcard_back VARCHAR(200) COMMENT '联系人身份证(反面)URL',
    contact_name VARCHAR(20) COMMENT '联系人姓名',
    contact_telephone VARCHAR(20) COMMENT '联系人电话',
    examine_state VARCHAR(4) DEFAULT '1' COMMENT '审核状态',
    balance VARCHAR(20) COMMENT '账户余额',
    meno VARCHAR(200) COMMENT '备注',
    fb1 VARCHAR(40) COMMENT '备用1',
    fb2 VARCHAR(20) COMMENT '备用2',
    fb3 VARCHAR(20) COMMENT '备用3',
    fb4 VARCHAR(200) COMMENT '备用4',
    fb5 VARCHAR(20) COMMENT '备用5',
    eb1 VARCHAR(40) COMMENT '扩展1',
    eb2 VARCHAR(80) COMMENT '扩展2',
    eb3 VARCHAR(20) COMMENT '扩展3',
    eb4 VARCHAR(10) COMMENT '扩展4',
    eb5 VARCHAR(20) COMMENT '扩展5',
    del_flag CHAR(1) DEFAULT '0' COMMENT '有效标识',
    create_time VARCHAR(24) DEFAULT '2017-12-12' NOT NULL COMMENT '创建时间',
    creator VARCHAR(20) DEFAULT 'SYSTEM' NOT NULL COMMENT '创建者',
    update_time VARCHAR(24) COMMENT '更新时间',
    updator VARCHAR(20) COMMENT '最后更新者',
PRIMARY KEY (puk)
) COMMENT '企业基本信息'
;
