CREATE TABLE u103010_recharge
(
    puk VARCHAR(20) NOT NULL COMMENT '流水ID',
    order_number VARCHAR(128) NOT NULL COMMENT '订单号',
    material_id VARCHAR(20) COMMENT '素材ID',
    material_classify VARCHAR(20) COMMENT '素材分类',
    material_tpe VARCHAR(20) COMMENT '素材类型',
    user_id VARCHAR(20) COMMENT '玩家流水ID',
    user_ip VARCHAR(80) COMMENT '用户当前IP',
    openid VARCHAR(80) COMMENT 'OpenID',
    user_phone VARCHAR(80) COMMENT '手机号码',
    pay_type VARCHAR(4) COMMENT '支付账户类别',
    recharge_money DECIMAL(10,2) COMMENT '充值金额',
    recharge_state VARCHAR(4) DEFAULT '2' COMMENT '充值状态',
    order_state VARCHAR(4) DEFAULT '2' COMMENT '订单状态',
    supplement_state VARCHAR(4) DEFAULT '2' COMMENT '补单状态',
    process_name VARCHAR(80) DEFAULT '2' COMMENT '业务实现类名',
    nonce_str VARCHAR(200) COMMENT '订单校验码',
    body VARCHAR(200) COMMENT '订单描述',
    meno VARCHAR(200) COMMENT '备注',
    fb1 VARCHAR(40) COMMENT '备用1',
    fb2 VARCHAR(20) COMMENT '备用2',
    fb3 VARCHAR(20) COMMENT '备用3',
    fb4 VARCHAR(200) COMMENT '备用4',
    fb5 VARCHAR(20) COMMENT '备用5',
    eb1 VARCHAR(40) COMMENT '扩展1',
    eb2 VARCHAR(80) COMMENT '扩展2',
    eb3 VARCHAR(20) COMMENT '扩展3',
    eb4 VARCHAR(10) COMMENT '扩展4',
    eb5 VARCHAR(20) COMMENT '扩展5',
    del_flag CHAR(1) DEFAULT '0' COMMENT '有效标识',
    create_time VARCHAR(24) DEFAULT '2017/6/27' NOT NULL COMMENT '创建时间',
    creator VARCHAR(20) DEFAULT 'SYSTEM' NOT NULL COMMENT '创建者',
    update_time VARCHAR(24) COMMENT '更新时间',
    updator VARCHAR(20) COMMENT '最后更新者',
PRIMARY KEY (puk)
) COMMENT '订单管理'
;
